[workspace]
members = [
  "schemas-rust",
  "program"
]
resolver = "2"

[workspace.dependencies]
flatbuffers = "23.5.26"
thiserror = "1.0.57"
solana-program = "=1.17.18"

[workspace.lints.clippy]
clone_on_ref_ptr = "deny"
missing_const_for_fn = "deny"
trivially_copy_pass_by_ref = "deny"
