// automatically generated by the FlatBuffers compiler, do not modify

import { TweedleDeeV1 } from './tweedle-dee-v1.js';
import { TweedleDumV1 } from './tweedle-dum-v1.js';


export enum FlatlanaInstructionData {
  NONE = 0,
  DeeV1 = 1,
  DumV1 = 2
}

export function unionToFlatlanaInstructionData(
  type: FlatlanaInstructionData,
  accessor: (obj:TweedleDeeV1|TweedleDumV1) => TweedleDeeV1|TweedleDumV1|null
): TweedleDeeV1|TweedleDumV1|null {
  switch(FlatlanaInstructionData[type]) {
    case 'NONE': return null; 
    case 'DeeV1': return accessor(new TweedleDeeV1())! as TweedleDeeV1;
    case 'DumV1': return accessor(new TweedleDumV1())! as TweedleDumV1;
    default: return null;
  }
}

export function unionListToFlatlanaInstructionData(
  type: FlatlanaInstructionData, 
  accessor: (index: number, obj:TweedleDeeV1|TweedleDumV1) => TweedleDeeV1|TweedleDumV1|null, 
  index: number
): TweedleDeeV1|TweedleDumV1|null {
  switch(FlatlanaInstructionData[type]) {
    case 'NONE': return null; 
    case 'DeeV1': return accessor(index, new TweedleDeeV1())! as TweedleDeeV1;
    case 'DumV1': return accessor(index, new TweedleDumV1())! as TweedleDumV1;
    default: return null;
  }
}
