// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { FlatlanaInstructionData, unionToFlatlanaInstructionData, unionListToFlatlanaInstructionData } from './flatlana-instruction-data.js';


export class FlatlanaInstruction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FlatlanaInstruction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFlatlanaInstruction(bb:flatbuffers.ByteBuffer, obj?:FlatlanaInstruction):FlatlanaInstruction {
  return (obj || new FlatlanaInstruction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFlatlanaInstruction(bb:flatbuffers.ByteBuffer, obj?:FlatlanaInstruction):FlatlanaInstruction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FlatlanaInstruction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

instructionType():FlatlanaInstructionData {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FlatlanaInstructionData.NONE;
}

instruction<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startFlatlanaInstruction(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addInstructionType(builder:flatbuffers.Builder, instructionType:FlatlanaInstructionData) {
  builder.addFieldInt8(0, instructionType, FlatlanaInstructionData.NONE);
}

static addInstruction(builder:flatbuffers.Builder, instructionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, instructionOffset, 0);
}

static endFlatlanaInstruction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFlatlanaInstructionBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedFlatlanaInstructionBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createFlatlanaInstruction(builder:flatbuffers.Builder, instructionType:FlatlanaInstructionData, instructionOffset:flatbuffers.Offset):flatbuffers.Offset {
  FlatlanaInstruction.startFlatlanaInstruction(builder);
  FlatlanaInstruction.addInstructionType(builder, instructionType);
  FlatlanaInstruction.addInstruction(builder, instructionOffset);
  return FlatlanaInstruction.endFlatlanaInstruction(builder);
}
}
