// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use crate::tweedle_dee_generated::*;
use crate::tweedle_dum_generated::*;
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_INSTRUCTION_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_INSTRUCTION_TYPE: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_INSTRUCTION_TYPE: [InstructionType; 3] = [
  InstructionType::Unknown,
  InstructionType::DeeV1,
  InstructionType::DumV1,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct InstructionType(pub u8);
#[allow(non_upper_case_globals)]
impl InstructionType {
  pub const Unknown: Self = Self(0);
  pub const DeeV1: Self = Self(1);
  pub const DumV1: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unknown,
    Self::DeeV1,
    Self::DumV1,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unknown => Some("Unknown"),
      Self::DeeV1 => Some("DeeV1"),
      Self::DumV1 => Some("DumV1"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for InstructionType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for InstructionType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for InstructionType {
    type Output = InstructionType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for InstructionType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for InstructionType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for InstructionType {}
pub enum FlatlanaInstructionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FlatlanaInstruction<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FlatlanaInstruction<'a> {
  type Inner = FlatlanaInstruction<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FlatlanaInstruction<'a> {
  pub const VT_IX_TYPE: flatbuffers::VOffsetT = 4;
  pub const VT_DEEV1: flatbuffers::VOffsetT = 6;
  pub const VT_DUMV1: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FlatlanaInstruction { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args FlatlanaInstructionArgs<'args>
  ) -> flatbuffers::WIPOffset<FlatlanaInstruction<'bldr>> {
    let mut builder = FlatlanaInstructionBuilder::new(_fbb);
    if let Some(x) = args.dumv1 { builder.add_dumv1(x); }
    if let Some(x) = args.deev1 { builder.add_deev1(x); }
    builder.add_ix_type(args.ix_type);
    builder.finish()
  }


  #[inline]
  pub fn ix_type(&self) -> InstructionType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<InstructionType>(FlatlanaInstruction::VT_IX_TYPE, Some(InstructionType::Unknown)).unwrap()}
  }
  #[inline]
  pub fn deev1(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(FlatlanaInstruction::VT_DEEV1, None)}
  }
  pub fn deev1_nested_flatbuffer(&'a self) -> Option<TweedleDeeV1<'a>> {
    self.deev1().map(|data| {
      use flatbuffers::Follow;
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid flatbuffer in this slot
      unsafe { <flatbuffers::ForwardsUOffset<TweedleDeeV1<'a>>>::follow(data.bytes(), 0) }
    })
  }
  #[inline]
  pub fn dumv1(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(FlatlanaInstruction::VT_DUMV1, None)}
  }
  pub fn dumv1_nested_flatbuffer(&'a self) -> Option<TweedleDumV1<'a>> {
    self.dumv1().map(|data| {
      use flatbuffers::Follow;
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid flatbuffer in this slot
      unsafe { <flatbuffers::ForwardsUOffset<TweedleDumV1<'a>>>::follow(data.bytes(), 0) }
    })
  }
}

impl flatbuffers::Verifiable for FlatlanaInstruction<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<InstructionType>("ix_type", Self::VT_IX_TYPE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("deev1", Self::VT_DEEV1, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("dumv1", Self::VT_DUMV1, false)?
     .finish();
    Ok(())
  }
}
pub struct FlatlanaInstructionArgs<'a> {
    pub ix_type: InstructionType,
    pub deev1: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub dumv1: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for FlatlanaInstructionArgs<'a> {
  #[inline]
  fn default() -> Self {
    FlatlanaInstructionArgs {
      ix_type: InstructionType::Unknown,
      deev1: None,
      dumv1: None,
    }
  }
}

pub struct FlatlanaInstructionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> FlatlanaInstructionBuilder<'a, 'b> {
  #[inline]
  pub fn add_ix_type(&mut self, ix_type: InstructionType) {
    self.fbb_.push_slot::<InstructionType>(FlatlanaInstruction::VT_IX_TYPE, ix_type, InstructionType::Unknown);
  }
  #[inline]
  pub fn add_deev1(&mut self, deev1: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FlatlanaInstruction::VT_DEEV1, deev1);
  }
  #[inline]
  pub fn add_dumv1(&mut self, dumv1: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(FlatlanaInstruction::VT_DUMV1, dumv1);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> FlatlanaInstructionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    FlatlanaInstructionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FlatlanaInstruction<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FlatlanaInstruction<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FlatlanaInstruction");
      ds.field("ix_type", &self.ix_type());
      ds.field("deev1", &self.deev1());
      ds.field("dumv1", &self.dumv1());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `FlatlanaInstruction`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_flatlana_instruction_unchecked`.
pub fn root_as_flatlana_instruction(buf: &[u8]) -> Result<FlatlanaInstruction, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<FlatlanaInstruction>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `FlatlanaInstruction` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_flatlana_instruction_unchecked`.
pub fn size_prefixed_root_as_flatlana_instruction(buf: &[u8]) -> Result<FlatlanaInstruction, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<FlatlanaInstruction>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `FlatlanaInstruction` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_flatlana_instruction_unchecked`.
pub fn root_as_flatlana_instruction_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<FlatlanaInstruction<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<FlatlanaInstruction<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `FlatlanaInstruction` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_flatlana_instruction_unchecked`.
pub fn size_prefixed_root_as_flatlana_instruction_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<FlatlanaInstruction<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<FlatlanaInstruction<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a FlatlanaInstruction and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `FlatlanaInstruction`.
pub unsafe fn root_as_flatlana_instruction_unchecked(buf: &[u8]) -> FlatlanaInstruction {
  flatbuffers::root_unchecked::<FlatlanaInstruction>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed FlatlanaInstruction and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `FlatlanaInstruction`.
pub unsafe fn size_prefixed_root_as_flatlana_instruction_unchecked(buf: &[u8]) -> FlatlanaInstruction {
  flatbuffers::size_prefixed_root_unchecked::<FlatlanaInstruction>(buf)
}
#[inline]
pub fn finish_flatlana_instruction_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<FlatlanaInstruction<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_flatlana_instruction_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<FlatlanaInstruction<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
