// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum TweedleDeeV1Offset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TweedleDeeV1<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TweedleDeeV1<'a> {
  type Inner = TweedleDeeV1<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TweedleDeeV1<'a> {
  pub const VT_THE_STRING: flatbuffers::VOffsetT = 4;
  pub const VT_THE_INT: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TweedleDeeV1 { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TweedleDeeV1Args<'args>
  ) -> flatbuffers::WIPOffset<TweedleDeeV1<'bldr>> {
    let mut builder = TweedleDeeV1Builder::new(_fbb);
    builder.add_the_int(args.the_int);
    if let Some(x) = args.the_string { builder.add_the_string(x); }
    builder.finish()
  }


  #[inline]
  pub fn the_string(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TweedleDeeV1::VT_THE_STRING, None)}
  }
  #[inline]
  pub fn the_int(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(TweedleDeeV1::VT_THE_INT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for TweedleDeeV1<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("the_string", Self::VT_THE_STRING, false)?
     .visit_field::<i32>("the_int", Self::VT_THE_INT, false)?
     .finish();
    Ok(())
  }
}
pub struct TweedleDeeV1Args<'a> {
    pub the_string: Option<flatbuffers::WIPOffset<&'a str>>,
    pub the_int: i32,
}
impl<'a> Default for TweedleDeeV1Args<'a> {
  #[inline]
  fn default() -> Self {
    TweedleDeeV1Args {
      the_string: None,
      the_int: 0,
    }
  }
}

pub struct TweedleDeeV1Builder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TweedleDeeV1Builder<'a, 'b> {
  #[inline]
  pub fn add_the_string(&mut self, the_string: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TweedleDeeV1::VT_THE_STRING, the_string);
  }
  #[inline]
  pub fn add_the_int(&mut self, the_int: i32) {
    self.fbb_.push_slot::<i32>(TweedleDeeV1::VT_THE_INT, the_int, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TweedleDeeV1Builder<'a, 'b> {
    let start = _fbb.start_table();
    TweedleDeeV1Builder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TweedleDeeV1<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TweedleDeeV1<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TweedleDeeV1");
      ds.field("the_string", &self.the_string());
      ds.field("the_int", &self.the_int());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `TweedleDeeV1`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tweedle_dee_v1_unchecked`.
pub fn root_as_tweedle_dee_v1(buf: &[u8]) -> Result<TweedleDeeV1, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<TweedleDeeV1>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TweedleDeeV1` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_tweedle_dee_v1_unchecked`.
pub fn size_prefixed_root_as_tweedle_dee_v1(buf: &[u8]) -> Result<TweedleDeeV1, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<TweedleDeeV1>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TweedleDeeV1` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tweedle_dee_v1_unchecked`.
pub fn root_as_tweedle_dee_v1_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TweedleDeeV1<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<TweedleDeeV1<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TweedleDeeV1` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tweedle_dee_v1_unchecked`.
pub fn size_prefixed_root_as_tweedle_dee_v1_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TweedleDeeV1<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<TweedleDeeV1<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TweedleDeeV1 and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TweedleDeeV1`.
pub unsafe fn root_as_tweedle_dee_v1_unchecked(buf: &[u8]) -> TweedleDeeV1 {
  flatbuffers::root_unchecked::<TweedleDeeV1>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TweedleDeeV1 and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TweedleDeeV1`.
pub unsafe fn size_prefixed_root_as_tweedle_dee_v1_unchecked(buf: &[u8]) -> TweedleDeeV1 {
  flatbuffers::size_prefixed_root_unchecked::<TweedleDeeV1>(buf)
}
#[inline]
pub fn finish_tweedle_dee_v1_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<TweedleDeeV1<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_tweedle_dee_v1_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<TweedleDeeV1<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
